webtalk_init -webtalk_dir C:\\Users\\mskreen.NI\\OneDrive\\Digilent\\Arty\\Arty_leds_sws\\Arty_leds_sws.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Aug 4 14:31:24 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ajvp5rgs7pb74462pi4an8lugo" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.2_15" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "15" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1438555255965" -context "sdk\\\\hardware/1438555255965"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1438555255965"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1438555255965"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.2" -context "sdk\\\\hardware/1438555255965"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1438555255965"
webtalk_add_data -client sdk -key Device -value "7a35ti" -context "sdk\\\\hardware/1438555255965"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1438555255965"
webtalk_add_data -client sdk -key uid -value "1438555568107" -context "sdk\\\\bsp/1438555568107"
webtalk_add_data -client sdk -key hwid -value "1438555255965" -context "sdk\\\\bsp/1438555568107"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1438555568107"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1438555568107"
webtalk_add_data -client sdk -key uid -value "1438555570796" -context "sdk\\\\application/1438555570796"
webtalk_add_data -client sdk -key hwid -value "1438555255965" -context "sdk\\\\application/1438555570796"
webtalk_add_data -client sdk -key bspid -value "1438555568107" -context "sdk\\\\application/1438555570796"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1438555570796"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1438555570796"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1438555570796"
webtalk_transmit -clientid 2154262810 -regid "" -xml C:\\Users\\mskreen.NI\\OneDrive\\Digilent\\Arty\\Arty_leds_sws\\Arty_leds_sws.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\mskreen.NI\\OneDrive\\Digilent\\Arty\\Arty_leds_sws\\Arty_leds_sws.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\mskreen.NI\\OneDrive\\Digilent\\Arty\\Arty_leds_sws\\Arty_leds_sws.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
