# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.cache/wt [current_project]
set_property parent.project_path C:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty:part0:1.1 [current_project]
add_files C:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_2/design_1_microblaze_0_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_2/design_1_microblaze_0_2_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_2/design_1_microblaze_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_2/design_1_dlmb_v10_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_2/design_1_dlmb_v10_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_2/design_1_ilmb_v10_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_2/design_1_ilmb_v10_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_2/design_1_dlmb_bram_if_cntlr_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_2/design_1_ilmb_bram_if_cntlr_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_2/design_1_lmb_bram_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_2/design_1_mdm_1_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_2/design_1_mdm_1_2_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_2/design_1_clk_wiz_1_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_2/design_1_clk_wiz_1_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_1_2/design_1_clk_wiz_1_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_2/design_1_rst_clk_wiz_1_100M_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_2/design_1_rst_clk_wiz_1_100M_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_2/design_1_rst_clk_wiz_1_100M_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_1/design_1_axi_uartlite_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_1/design_1_axi_uartlite_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_1/design_1_axi_uartlite_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files C:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib C:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_leds_sws/Arty_leds_sws.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
read_xdc C:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_Master.xdc
set_property used_in_implementation false [get_files C:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top design_1_wrapper -part xc7a35ticsg324-1L
write_checkpoint -noxdef design_1_wrapper.dcp
catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
