# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_Programming_Guide_Demo/Arty_Programming_Guide_Demo.cache/wt [current_project]
set_property parent.project_path C:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_Programming_Guide_Demo/Arty_Programming_Guide_Demo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty:part0:1.1 [current_project]
read_verilog -library xil_defaultlib C:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_Programming_Guide_Demo/Arty_Programming_Guide_Demo.srcs/sources_1/new/sw_led.v
read_xdc C:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_Programming_Guide_Demo/Arty_Programming_Guide_Demo.srcs/constrs_1/imports/Arty/Arty_Master.xdc
set_property used_in_implementation false [get_files C:/Users/mskreen.NI/OneDrive/Digilent/Arty/Arty_Programming_Guide_Demo/Arty_Programming_Guide_Demo.srcs/constrs_1/imports/Arty/Arty_Master.xdc]

synth_design -top sw_btn_led -part xc7a35ticsg324-1L
write_checkpoint -noxdef sw_btn_led.dcp
catch { report_utilization -file sw_btn_led_utilization_synth.rpt -pb sw_btn_led_utilization_synth.pb }
