# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/eth_ref_clk.xdc

# Block Designs: bd/Mb_Server/Mb_Server.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server || ORIG_REF_NAME==Mb_Server}]

# IP: bd/Mb_Server/ip/Mb_Server_microblaze_0_0/Mb_Server_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_microblaze_0_0 || ORIG_REF_NAME==Mb_Server_microblaze_0_0}]

# IP: bd/Mb_Server/ip/Mb_Server_dlmb_v10_0/Mb_Server_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_dlmb_v10_0 || ORIG_REF_NAME==Mb_Server_dlmb_v10_0}]

# IP: bd/Mb_Server/ip/Mb_Server_ilmb_v10_0/Mb_Server_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_ilmb_v10_0 || ORIG_REF_NAME==Mb_Server_ilmb_v10_0}]

# IP: bd/Mb_Server/ip/Mb_Server_dlmb_bram_if_cntlr_0/Mb_Server_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Mb_Server_dlmb_bram_if_cntlr_0}]

# IP: bd/Mb_Server/ip/Mb_Server_ilmb_bram_if_cntlr_0/Mb_Server_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Mb_Server_ilmb_bram_if_cntlr_0}]

# IP: bd/Mb_Server/ip/Mb_Server_lmb_bram_0/Mb_Server_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_lmb_bram_0 || ORIG_REF_NAME==Mb_Server_lmb_bram_0}]

# IP: bd/Mb_Server/ip/Mb_Server_microblaze_0_axi_periph_0/Mb_Server_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Mb_Server_microblaze_0_axi_periph_0}]

# IP: bd/Mb_Server/ip/Mb_Server_microblaze_0_axi_intc_0/Mb_Server_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Mb_Server_microblaze_0_axi_intc_0}]

# IP: bd/Mb_Server/ip/Mb_Server_microblaze_0_xlconcat_0/Mb_Server_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_microblaze_0_xlconcat_0 || ORIG_REF_NAME==Mb_Server_microblaze_0_xlconcat_0}]

# IP: bd/Mb_Server/ip/Mb_Server_mdm_1_0/Mb_Server_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_mdm_1_0 || ORIG_REF_NAME==Mb_Server_mdm_1_0}]

# IP: bd/Mb_Server/ip/Mb_Server_clk_wiz_1_0/Mb_Server_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_clk_wiz_1_0 || ORIG_REF_NAME==Mb_Server_clk_wiz_1_0}]

# IP: bd/Mb_Server/ip/Mb_Server_rst_clk_wiz_1_100M_0/Mb_Server_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Mb_Server_rst_clk_wiz_1_100M_0}]

# IP: bd/Mb_Server/ip/Mb_Server_mig_7series_0_0/Mb_Server_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_mig_7series_0_0 || ORIG_REF_NAME==Mb_Server_mig_7series_0_0}]

# IP: bd/Mb_Server/ip/Mb_Server_axi_uartlite_0_0/Mb_Server_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_axi_uartlite_0_0 || ORIG_REF_NAME==Mb_Server_axi_uartlite_0_0}]

# IP: bd/Mb_Server/ip/Mb_Server_axi_ethernetlite_0_0/Mb_Server_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_axi_ethernetlite_0_0 || ORIG_REF_NAME==Mb_Server_axi_ethernetlite_0_0}]

# IP: bd/Mb_Server/ip/Mb_Server_axi_timer_0_0/Mb_Server_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_axi_timer_0_0 || ORIG_REF_NAME==Mb_Server_axi_timer_0_0}]

# IP: bd/Mb_Server/ip/Mb_Server_axi_mem_intercon_0/Mb_Server_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_axi_mem_intercon_0 || ORIG_REF_NAME==Mb_Server_axi_mem_intercon_0}]

# IP: bd/Mb_Server/ip/Mb_Server_xbar_0/Mb_Server_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_xbar_0 || ORIG_REF_NAME==Mb_Server_xbar_0}]

# IP: bd/Mb_Server/ip/Mb_Server_rst_mig_7series_0_83M_0/Mb_Server_rst_mig_7series_0_83M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==Mb_Server_rst_mig_7series_0_83M_0}]

# IP: bd/Mb_Server/ip/Mb_Server_xbar_1/Mb_Server_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_xbar_1 || ORIG_REF_NAME==Mb_Server_xbar_1}]

# IP: bd/Mb_Server/ip/Mb_Server_auto_cc_0/Mb_Server_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_auto_cc_0 || ORIG_REF_NAME==Mb_Server_auto_cc_0}]

# IP: bd/Mb_Server/ip/Mb_Server_auto_us_0/Mb_Server_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_auto_us_0 || ORIG_REF_NAME==Mb_Server_auto_us_0}]

# IP: bd/Mb_Server/ip/Mb_Server_auto_us_1/Mb_Server_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_auto_us_1 || ORIG_REF_NAME==Mb_Server_auto_us_1}]

# XDC: bd/Mb_Server/ip/Mb_Server_microblaze_0_0/Mb_Server_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Mb_Server_microblaze_0_0 || ORIG_REF_NAME==Mb_Server_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/Mb_Server/ip/Mb_Server_microblaze_0_0/Mb_Server_microblaze_0_0_ooc_debug.xdc

# XDC: bd/Mb_Server/ip/Mb_Server_microblaze_0_0/Mb_Server_microblaze_0_0_ooc.xdc

# XDC: bd/Mb_Server/ip/Mb_Server_dlmb_v10_0/Mb_Server_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Mb_Server_dlmb_v10_0 || ORIG_REF_NAME==Mb_Server_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/Mb_Server/ip/Mb_Server_dlmb_v10_0/Mb_Server_dlmb_v10_0_ooc.xdc

# XDC: bd/Mb_Server/ip/Mb_Server_ilmb_v10_0/Mb_Server_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Mb_Server_ilmb_v10_0 || ORIG_REF_NAME==Mb_Server_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/Mb_Server/ip/Mb_Server_ilmb_v10_0/Mb_Server_ilmb_v10_0_ooc.xdc

# XDC: bd/Mb_Server/ip/Mb_Server_dlmb_bram_if_cntlr_0/Mb_Server_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/Mb_Server/ip/Mb_Server_ilmb_bram_if_cntlr_0/Mb_Server_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/Mb_Server/ip/Mb_Server_lmb_bram_0/Mb_Server_lmb_bram_0_ooc.xdc

# XDC: bd/Mb_Server/ip/Mb_Server_microblaze_0_axi_intc_0/Mb_Server_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Mb_Server_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Mb_Server_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/Mb_Server/ip/Mb_Server_microblaze_0_axi_intc_0/Mb_Server_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Mb_Server_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Mb_Server_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/Mb_Server/ip/Mb_Server_microblaze_0_axi_intc_0/Mb_Server_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/Mb_Server/ip/Mb_Server_mdm_1_0/Mb_Server_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Mb_Server_mdm_1_0 || ORIG_REF_NAME==Mb_Server_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/Mb_Server/ip/Mb_Server_mdm_1_0/Mb_Server_mdm_1_0_ooc_trace.xdc

# XDC: bd/Mb_Server/ip/Mb_Server_clk_wiz_1_0/Mb_Server_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Mb_Server_clk_wiz_1_0 || ORIG_REF_NAME==Mb_Server_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/Mb_Server/ip/Mb_Server_clk_wiz_1_0/Mb_Server_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Mb_Server_clk_wiz_1_0 || ORIG_REF_NAME==Mb_Server_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/Mb_Server/ip/Mb_Server_clk_wiz_1_0/Mb_Server_clk_wiz_1_0_ooc.xdc

# XDC: bd/Mb_Server/ip/Mb_Server_rst_clk_wiz_1_100M_0/Mb_Server_rst_clk_wiz_1_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Mb_Server_rst_clk_wiz_1_100M_0}]

# XDC: bd/Mb_Server/ip/Mb_Server_rst_clk_wiz_1_100M_0/Mb_Server_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Mb_Server_rst_clk_wiz_1_100M_0}]

# XDC: bd/Mb_Server/ip/Mb_Server_rst_clk_wiz_1_100M_0/Mb_Server_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/Mb_Server/ip/Mb_Server_mig_7series_0_0/Mb_Server_mig_7series_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_mig_7series_0_0 || ORIG_REF_NAME==Mb_Server_mig_7series_0_0}]

# XDC: bd/Mb_Server/ip/Mb_Server_axi_uartlite_0_0/Mb_Server_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Mb_Server_axi_uartlite_0_0 || ORIG_REF_NAME==Mb_Server_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/Mb_Server/ip/Mb_Server_axi_uartlite_0_0/Mb_Server_axi_uartlite_0_0_ooc.xdc

# XDC: bd/Mb_Server/ip/Mb_Server_axi_uartlite_0_0/Mb_Server_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Mb_Server_axi_uartlite_0_0 || ORIG_REF_NAME==Mb_Server_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/Mb_Server/ip/Mb_Server_axi_ethernetlite_0_0/Mb_Server_axi_ethernetlite_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_axi_ethernetlite_0_0 || ORIG_REF_NAME==Mb_Server_axi_ethernetlite_0_0}]

# XDC: bd/Mb_Server/ip/Mb_Server_axi_ethernetlite_0_0/Mb_Server_axi_ethernetlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_axi_ethernetlite_0_0 || ORIG_REF_NAME==Mb_Server_axi_ethernetlite_0_0}]

# XDC: bd/Mb_Server/ip/Mb_Server_axi_ethernetlite_0_0/Mb_Server_axi_ethernetlite_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_axi_ethernetlite_0_0 || ORIG_REF_NAME==Mb_Server_axi_ethernetlite_0_0}]

# XDC: bd/Mb_Server/ip/Mb_Server_axi_ethernetlite_0_0/Mb_Server_axi_ethernetlite_0_0_ooc.xdc

# XDC: bd/Mb_Server/ip/Mb_Server_axi_timer_0_0/Mb_Server_axi_timer_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_axi_timer_0_0 || ORIG_REF_NAME==Mb_Server_axi_timer_0_0}]

# XDC: bd/Mb_Server/ip/Mb_Server_axi_timer_0_0/Mb_Server_axi_timer_0_0_ooc.xdc

# XDC: bd/Mb_Server/ip/Mb_Server_xbar_0/Mb_Server_xbar_0_ooc.xdc

# XDC: bd/Mb_Server/ip/Mb_Server_rst_mig_7series_0_83M_0/Mb_Server_rst_mig_7series_0_83M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==Mb_Server_rst_mig_7series_0_83M_0}]

# XDC: bd/Mb_Server/ip/Mb_Server_rst_mig_7series_0_83M_0/Mb_Server_rst_mig_7series_0_83M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mb_Server_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==Mb_Server_rst_mig_7series_0_83M_0}]

# XDC: bd/Mb_Server/ip/Mb_Server_rst_mig_7series_0_83M_0/Mb_Server_rst_mig_7series_0_83M_0_ooc.xdc

# XDC: bd/Mb_Server/ip/Mb_Server_xbar_1/Mb_Server_xbar_1_ooc.xdc

# XDC: bd/Mb_Server/ip/Mb_Server_auto_cc_0/Mb_Server_auto_cc_0_ooc.xdc

# XDC: bd/Mb_Server/ip/Mb_Server_auto_cc_0/Mb_Server_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Mb_Server_auto_cc_0 || ORIG_REF_NAME==Mb_Server_auto_cc_0}] {/inst }]/inst ]]

# XDC: bd/Mb_Server/ip/Mb_Server_auto_us_0/Mb_Server_auto_us_0_ooc.xdc

# XDC: bd/Mb_Server/ip/Mb_Server_auto_us_0/Mb_Server_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Mb_Server_auto_us_0 || ORIG_REF_NAME==Mb_Server_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/Mb_Server/ip/Mb_Server_auto_us_1/Mb_Server_auto_us_1_ooc.xdc

# XDC: bd/Mb_Server/ip/Mb_Server_auto_us_1/Mb_Server_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Mb_Server_auto_us_1 || ORIG_REF_NAME==Mb_Server_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/Mb_Server/Mb_Server_ooc.xdc
